import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import { ppneuemontreal } from "../app/helpers/fonts";
import SmoothScrolling from "./helpers/SmoothScrolling";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //#fafafa

  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/_next/static/media/d6d1a7d2e448e5b5-s.p.otf"
          fetchPriority="high"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={`${ppneuemontreal.className} antialiased bg-[#EDE9DE]`}>
        <SmoothScrolling>
          <Suspense>{children}</Suspense>
          <div className="noise-bg"></div>
        </SmoothScrolling>
      </body>
    </html>
  );
}
