import type { Metadata } from "next";
import "./globals.css";
import { ppneuemontreal } from "../app/helpers/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //previously bg was #fafafa
  return (
    <html lang="en">
      <body className={`${ppneuemontreal.className} antialiased bg-primary`}>
        {children}
        <div className="noise-bg"></div>
      </body>
    </html>
  );
}
